name: student_application
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0 
  firebase_auth: ^4.11.0  
  shared_preferences: ^2.0.15
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.0.6
  google_sign_in: ^5.0.7
  image_picker: ^1.0.7
  url_launcher: ^6.1.14    
  file_picker: ^6.1.1
  uuid: ^4.2.2
  path_provider: ^2.1.2 
  intl: ^0.17.0
  flutter_pdfview: ^1.2.5
  path: ^1.8.3
  bcrypt: ^1.1.3



 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0



flutter:

 
  uses-material-design: true


